"""Updated schema of user model

Revision ID: 1f431319ef89
Revises: 
Create Date: 2024-11-17 18:08:20.547392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f431319ef89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('experiences', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('educations', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('certifications', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('certifications')
        batch_op.drop_column('skills')
        batch_op.drop_column('educations')
        batch_op.drop_column('experiences')
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('bio')
        batch_op.drop_column('phone')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
